version: '3.7'
services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_USER: root
            MYSQL_DATABASE: memobeer
        ports:
            - '3306'
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    mailer:
        image: schickling/mailcatcher
        ports: [ 1025, 1080 ]
